# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5758c92fdeac273d5dcd43708a00b2410e661592a47c95a41bec08aa4b8da6152b41d642ca4699e08565200589573804d5393c40df77e4e917e83bb718058e8

test:
  secret_key_base: 224c14e75d78de57566450e1f51976e0a7cc1d8c0b21acb1b85ac290fa01a34767f5a6ea6afe6db37e706fa1bceab25f36bee3098e3ec8d44133985b1bbf97f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
